### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ghost** [maxgillham/ReinforcementLearning-AlgoTrading#13]
Hello.

I am currently trying to test it. So, I run python3 main.py iid, I got

For Source IID
***Episiode Number***...
...

Basically, if I am right, now it should be “learning”. Well, what to do then? What is the data input and where can I test it after that? Thanks.

**Comment by pico6855** [comment]
The result has just shown. What next can I do with it?

**Comment by maxgillham** [comment]
The input data here is as you specified in the command, a sampled independent identically distributed random variable.  The possible return rates and distribution can be specified in `utils.py`.  
The purpose of this is to determine the feasibility of applying Q-learning to this sample knowing the distribution of the source.
